// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlq5axei_TvTAoZrmDd7VxmB3GDfGYbrE',
    appId: '1:634862114444:web:7087ea9efb4aa7ffe40da9',
    messagingSenderId: '634862114444',
    projectId: 'lifeos-80f46',
    authDomain: 'lifeos-80f46.firebaseapp.com',
    storageBucket: 'lifeos-80f46.firebasestorage.app',
    measurementId: 'G-EPNM2216KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKmA8YMJ9AUOdN7u7QZXgITnlS-LI1U0',
    appId: '1:634862114444:android:2325c858e09e05cee40da9',
    messagingSenderId: '634862114444',
    projectId: 'lifeos-80f46',
    storageBucket: 'lifeos-80f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjen1PGKdM6X-6T9E7r9p91dNvDNGn6I',
    appId: '1:634862114444:ios:46e34b33da729bb5e40da9',
    messagingSenderId: '634862114444',
    projectId: 'lifeos-80f46',
    storageBucket: 'lifeos-80f46.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjen1PGKdM6X-6T9E7r9p91dNvDNGn6I',
    appId: '1:634862114444:ios:46e34b33da729bb5e40da9',
    messagingSenderId: '634862114444',
    projectId: 'lifeos-80f46',
    storageBucket: 'lifeos-80f46.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlq5axei_TvTAoZrmDd7VxmB3GDfGYbrE',
    appId: '1:634862114444:web:8d9f6e23db4b6b80e40da9',
    messagingSenderId: '634862114444',
    projectId: 'lifeos-80f46',
    authDomain: 'lifeos-80f46.firebaseapp.com',
    storageBucket: 'lifeos-80f46.firebasestorage.app',
    measurementId: 'G-VR688FWRKF',
  );
}
